# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  
  # enable for internet
  config.vm.network "public_network"

  config.vm.synced_folder ".", "/home/" 
    config.vm.define "controlnode" do |controlnode|
      controlnode.vm.box = "centos/7"
      controlnode.vm.hostname = "controlnode.naren.com"
      controlnode.vm.network "private_network", ip: "172.42.42.100"
      controlnode.vm.provider "virtualbox" do |v|
        v.name = "controlnode"
        v.memory = 1024
        v.cpus = 1
        # Prevent VirtualBox from interfering with host audio stack
        v.customize ["modifyvm", :id, "--audio", "none"]
      end
      
    end
    config.vm.provision "shell", path: "bootstrap.sh" , run: "always"  
end
